### ISSUE TITLE
Problem with punctuation in pre-tokenized text

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/classla-stanfordnlp#20]
I am annotating a pre-tokenised corpus, so I used:
```
classla.Pipeline('sl', tokenize_pretokenized=True, processors='tokenize,pos,lemma', pos_use_lexicon=True)
```
and put the input (as the documentation says) as space separated text, one sentence per line, e.g.
```
ja !
kaj ?
in , kaj ; potem / misliš .
```

But it turns out that most of the punctuation tokens are lemmatised as the copyright symbol, and all have a wrong XPOS, i.e.
```
2021-06-21 14:47:11 INFO: Use device: cpu
2021-06-21 14:47:11 INFO: Loading: tokenize
2021-06-21 14:47:11 INFO: Loading: pos
2021-06-21 14:47:21 INFO: Loading: lemma
2021-06-21 14:47:26 INFO: Done loading processors!
1       ja      ja      PART    Q       _       _       _       _       start_char=0|end_char=2
2       !       ©       PUNCT   Agpfdd  _       _       _       _       start_char=3|end_char=4

1       kaj     kaj     PRON    Pq-nsn  Case=Nom|Gender=Neut|Number=Sing|PronType=Int   _       _       _       start_char=5|end_char=8
2       ?       ©       PUNCT   Agpfdd  _       _       _       _       start_char=9|end_char=10

1       in      in      CCONJ   Cc      _       _       _       _       start_char=11|end_char=13
2       ,       ,       PUNCT   I       _       _       _       _       start_char=14|end_char=15
3       kaj     kaj     PRON    Pq-nsn  Case=Nom|Gender=Neut|Number=Sing|PronType=Int   _       _       _       start_char=16|end_char=19
4       ;       ©       PUNCT   Agpfdd  _       _       _       _       start_char=20|end_char=21
5       potem   potem   ADV     Rgp     Degree=Pos      _       _       _       start_char=22|end_char=27
6       /       ©       PUNCT   Agpfdd  _       _       _       _       start_char=28|end_char=29
7       misliš  misliti VERB    Vmpr2s  Aspect=Imp|Mood=Ind|Number=Sing|Person=2|Tense=Pres|VerbForm=Fin        _       _       _       start_char=30|end_char=36
8       .       .       PUNCT   I       _       _       _       _       start_char=37|end_char=38
```

Note that if tokenisation is performed on plain text by classla, it works fine.

**Comment by lkrsnik** [comment]
These errors occur because of `pos_use_lexicon=True` and `tokenize_pretokenized=True` combination. When we have use_lexicon tag, we assume that xpos tags for punctuations were annotated by tokeniser. That is why xpos tag 'Z' will never be predicted (it is in closed_classes), only propagated from tokeniser.

Since, we have had similar issues already, I suggest we implement a better solution than ugly workarounds that could be done to run this code correctly. A couple of suggestions:
- We introduce another attribute, something like `pos_annotate_punct`, that tells us if we add 'Z' to xpos closed_classes (I think this would be the easiest solution). The default for this should be True, so that we don't ruin all existing pipelines.
- We could have a hidden attribute `pos_annotate_punct` that is tightly connected to attribute `tokenize_pretokenized`. It could be True only when `tokenize_pretokenized` is 'conllu'. However, if user would have conllu pretokenized text without pos tags, we would have the same issue as here.

**Comment by TomazErjavec** [comment]
> When we have use_lexicon tag, we assume that xpos tags for punctuations were annotated by tokeniser.

Does the tokeniser use the lexicon at all? If it does, it should not be too hard to add all punctuation symbols to it. As an addition or alternative to the proposed solutions. If it does not, then the first solution sounds ok to me.

**Comment by nljubesi** [comment]
Would it not be simplest, if the `tokenize_pretokenized=True` argument is given, to run the tagging as if reldi-tokeniser was used for tokenization (we have a list of punctuations for this case)?

@lkrsnik, we can also chat (I will be on Skype until 8ish) if necessary.

**Comment by lkrsnik** [comment]
The code, that was used when `pos_use_lexicon=True`, was expanded so that when we use `tokenize_pretokenized=True` or `tokenize_pretokenized="conllu"` we no longer use pre-annotated punctuations.

The change is visible in the latest commit and will be published on pypi with the next release.
