### ISSUE TITLE
Lemmatization and ner mistakes 

### ISSUE THREAD

**Issue by matejMartinc** [clarinsi/classla-stanfordnlp#26]
Hey, I'm just giving some feedback on the lemmatization and ner mistakes that I noticed using classla. Not sure this is fixable though?

Lemmatization:
portalom gets  lemmatized to portalo pretty much all the time
kripto gets lemmatized to kripta

To reproduce:

nlp_slo = classla.Pipeline(lang='sl', processors='tokenize,ner,pos,lemma')
doc = nlp_slo('Nad kamnitim portalom je naslikan grb z letnico 1735.')
doc = nlp_slo('Brezplačni priročnik Kako trgovati s ceno kripto valut prevzemite tukaj.')

NER: 

Named entites that appear at the beginning of the sentence tend to not be recognized as named entities, especially if these NE also have another meaning. Extending the context (i.e., by feeding the model an entire document instead of just a single sentence) does not help:

Input examples:

nlp_slo = classla.Pipeline(lang='sl', processors='tokenize,ner,pos,lemma')

doc = nlp_slo('Kurz je 27. januarja na mednarodni dan spomina na holokavst javno priznal sporno vlogo Avstrije pri tem zločinu in hkrati tudi njeno odgovornost.')
doc = nlp_slo('Inter skuša pripeljati kapetana hrvaške reprezentance Luko Modrića, mestni tekmec Milan pa Matea Kovačića.')
doc = nlp_slo('West je v karieri igral tudi za New Orleans, Indiano in San Antonio')

Environment (please complete the following information):**
 - OS: Linux Mint
 - Python version: 3.8.10
 - Classla version: 1.0.2

**Comment by nljubesi** [comment]
Thank you  for your feedback, much appreciated!

This is all mostly due to background training data and ambiguity. Only one issue can be resolved with a new feature (`pos_use_lexicon`), namely the `portalom` one.

```
nlp_slo = classla.Pipeline(lang='sl', processors='tokenize,ner,pos,lemma', pos_use_lexicon=True)
doc = nlp_slo('Nad kamnitim portalom je naslikan grb z letnico 1735.')
```

Be careful with the application of this lexicon usage during tagging as it does not allow for any contextually-sound tags for tokens that are covered by the lexicon, but not with that tag.

For all other issues training data closer to the examples should be provided.
