### ISSUE TITLE
Longer texts cannot be processed

### ISSUE THREAD

**Issue by kkac26** [clarinsi/classla-stanfordnlp#4]
I want to process longer text, such as [thesis](https://github.com/clarinsi/classla-stanfordnlp/files/5238993/demofile.txt) in attachment. Stanza library works fine, but Classla is crashing when processing longer texts.

Code:
```
import sys
import classla
sys.setrecursionlimit(50000)

classla.download('sl')
nlpSlo = classla.Pipeline('sl', processors='tokenize,ner,pos,lemma,depparse')

f=open("demofile.txt", "r", encoding="utf-8")
plainText=f.read()

doc = nlpSlo(plainText)
conllu = doc.conll_file.conll_as_string()

print(conllu)
```

Error:
`MemoryError: Unable to allocate 45.8 MiB for an array with shape (2450, 2450) and data type float64`

**Comment by nljubesi** [comment]
Thank you @klemenkac for reporting this.

When I try reproducing your code, I get in all cases (classla, GPU, non-GPU, same for stanza) a RecursionError (maximum recursion depth exceeded while calling a Python object) due to the facts that (1) you do not have newlines encoded in your text and (2) a good part of your text is numerical data, which ends up being VERY long sentences that cannot be dependency parsed with the recursion depth limitations set. Did you, by any chance, extend the maximum recursion depth?

In general, I suggest you (1) keep your newlines as these are important cues for text segmentation, (2) potentially clean-up your text slightly before NLP processing (removing long numerical sequences and similar), and (3) potentially feed smaller parts of the text into the pipeline. I would really love to hear more feedback from you on your experiences with stanza and classla.

@lkrsnik I noticed that the stanza models are loading MUCH faster, I guess they did some optimization recently, it might be they also did additional optimizations since the moment we forked from them, so I suggest, once we are done with the current improvements on the tagger+lexicon task (redmine), we define a task consisting of analyzing the code modifications performed in stanza and potentially implementing some of those on our side.

**Comment by kkac26** [comment]
@nljubesi Yes, I extended maximum resursion depth to 50000 when I used classla/stanza. Stanza's library is processing files like this (and even bigger) with no problem and is also significally faster than classla. Classla is using too much resources and often throws MemoryError's like the one in my first post or this one:

`[enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 66881920000 bytes. Buy new RAM!`

I have 500GB of RAM and I do not plan to buy new one. I suspect there must be some kind of Memory leak. I could manually split my text to several sentences and then feed sentences one after one into the pipeline, but this is something I would expect your library to be able to do.

**Comment by nljubesi** [comment]
classla is actually a fork of stanza, so there must have been optimizations going on on the side of stanza in the meantime. If you have the capacity to inspect the improvements made in stanza, feel free to open a branch and improve our code!

If not, then these improvements will have to wait for our developers to find the necessary time.

**Comment by nljubesi** [comment]
We recently updated classla so that it now seamlessly processes documents of length of hundreds of thousands of tokens.
